spring:
  datasource:
    url: jdbc:mysql://118.31.60.32:3306
    driverClassName: com.mysql.cj.jdbc.Driver
    username: g06
    password: g06
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: g06/ecnu/heartbridge/entity