spring:
  application:
    name: heartbridge
  profiles:
    active: dev,ltdz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    g06:
      ecnu:
        heartbridge:
          mapper: debug
          service: debug
          entity: debug
          controller: debug
    org:
      mybatis: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: g06/ecnu/heartbridge/entity