spring:
  application:
    name: heartbridge
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  task:
    scheduling:
      pool:
        size: 5
  web:
    resources:
      static-locations: file:///C:/Users/minam/Desktop/image/, classpath:/static
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.60.32:3306/phy_test
    username: g06
    password: g06
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  servlet:
    session:
      timeout: 30m
  port: 8888

logging:
  level:
    g06:
      ecnu:
        heartbridge:
          mapper: debug
          service: debug
          entity: debug
          controller: debug
    org:
      mybatis: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: g06/ecnu/heartbridge/entity

image-upload:
  path: file:///C:/Users/minam/Desktop/image/